import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  linuxSidebar: [{ type: "autogenerated", dirName: "linux" }],
  kubernetesSidebar: [{ type: "autogenerated", dirName: "kubernetes" }],
  gitopsSidebar: [{ type: "autogenerated", dirName: "gitops" }],
  monitoringSidebar: [
    "monitoring/monitoring-architecture",
    {
      type: "category",
      label: "Prometheus",
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "monitoring/prometheus" }],
    },
    {
      type: "category",
      label: "Alertmanager",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "monitoring/alertmanager" }],
    },
    {
      type: "category",
      label: "Grafana",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "monitoring/grafana" }],
    },
  ],
  dockerSidebar: [{ type: "autogenerated", dirName: "docker" }],
  databaseSidebar: [{ type: "autogenerated", dirName: "database" }],
  messageQueueSidebar: [{ type: "autogenerated", dirName: "message-queue" }],
};

export default sidebars;
