import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  opsSidebar: [
    "intro",
    {
      type: "category",
      label: "Platform 集群平台",
      items: [{ type: "autogenerated", dirName: "platform" }],
    },
    {
      type: "category",
      label: "Observability 可观测",
      items: [{ type: "autogenerated", dirName: "observability" }],
    },
    {
      type: "category",
      label: "Automation 自动化",
      items: [{ type: "autogenerated", dirName: "automation" }],
    },
    {
      type: "category",
      label: "Data 数据库",
      items: [{ type: "autogenerated", dirName: "data" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
