import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  devopsSidebar: [{ type: "autogenerated", dirName: "devops" }],
  shellSidebar: [{ type: "autogenerated", dirName: "shell" }],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
};

export default sidebars;
