import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  linuxSidebar: [{ type: "autogenerated", dirName: "linux" }],
  kubernetesSidebar: [{ type: "autogenerated", dirName: "kubernetes" }],
  gitopsSidebar: [{ type: "autogenerated", dirName: "gitops" }],
  prometheusSidebar: [{ type: "autogenerated", dirName: "prometheus" }],
  dockerSidebar: [{ type: "autogenerated", dirName: "docker" }],
  databaseSidebar: [{ type: "autogenerated", dirName: "database" }],
  messageQueueSidebar: [{ type: "autogenerated", dirName: "message-queue" }],
};

export default sidebars;
