import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  kubernetesSidebar: [{ type: "autogenerated", dirName: "kubernetes" }],
  prometheusSidebar: [{ type: "autogenerated", dirName: "prometheus" }],
  devopsSidebar: [{ type: "autogenerated", dirName: "devops" }],
  databaseSidebar: [{ type: "autogenerated", dirName: "database" }],
  messageQueueSidebar: [{ type: "autogenerated", dirName: "message-queue" }],
  dockerSidebar: [{ type: "autogenerated", dirName: "docker" }],
  shellSidebar: [{ type: "autogenerated", dirName: "shell" }],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
};

export default sidebars;
